# Generated by Django 6.1.1 on 2026-09-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SavedSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="뉴스 제목")),
                ("summary", models.TextField(verbose_name="요약 본문")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="저장 시간")),
                (
                    "link",
                    models.URLField(
                        blank=True, default="", max_length=1000, verbose_name="기사 원문 링크"
                    ),
                ),
                ("reason", models.TextField(blank=True, default="", verbose_name="AI 선정 이유")),
                ("insight", models.TextField(blank=True, default="", verbose_name="핵심 인사이트")),
                (
                    "keyword",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="검색 키워드"
                    ),
                ),
            ],
            options={
                "verbose_name": "저장된 뉴스 요약",
                "verbose_name_plural": "저장된 뉴스 요약 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
